name: Terraform CI/CD Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

env:
  TF_LOG: INFO
  AWS_REGION: ap-northeast-1

jobs:
  terraform-test:
    name: Terraform Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Create tfvars file
        run: |
          cat > terraform.tfvars << EOF
          aws_region  = "${{ env.AWS_REGION }}"
          aws_profile = ""  # Not needed when using GitHub Actions credentials
          prefix      = "ci-test"
          
          ec2_instance_type   = "t3.small"  # Using smaller instance to save costs in CI
          ec2_ami_id          = "ami-0599b6e53ca798bb2"
          ssh_public_key_path = "~/.ssh/id_rsa.pub"
          
          s3_bucket_prefix = "logs-test"
          sqs_queue_name   = "s3-notifications-test"
          lambda_log_level = "INFO"
          default_tags = {
            division   = "platform"
            org        = "engineering"
            keep-until = "2026-01-01"
            team       = "observability"
            project    = "elastic-monitoring"
          }
          EOF

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve tfplan
        
      - name: Wait for Resources to be Ready
        run: sleep 60  # Wait a minute for resources to be fully provisioned

      - name: Test Lambda Function
        run: |
          # Install Python dependencies
          pip install boto3

          # First, store the Lambda function name in a file to avoid any issues with command substitution
          terraform output -raw lambda_function_name > lambda_name.txt
          LAMBDA_FUNCTION=$(cat lambda_name.txt)
          echo "Lambda function name: $LAMBDA_FUNCTION"
          
          # Now use the variable to invoke the Lambda function
          python invoke_lambda.py "$LAMBDA_FUNCTION" --count 5 --log-level INFO --delay 5

          # Sleep to allow logs to propagate to CloudWatch
          sleep 30
          
          # Get the CloudWatch log group name from Terraform output
          LOG_GROUP=$(terraform output -raw cloudwatch_log_group)
          
          # Check if logs were created
          LOG_EVENTS=$(aws logs describe-log-streams --log-group-name $LOG_GROUP --max-items 5)
          if [ -z "$LOG_EVENTS" ]; then
            echo "No log events found in CloudWatch log group $LOG_GROUP"
            exit 1
          fi
          
          echo "Successfully verified Lambda logs are being generated"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        if: always()  # Always run this step, even if previous steps fail